-- -- -- --
select table_name
  from user_tables;

create table departments (
   id   number
      generated by default as identity start with 10 increment by 10
   primary key,
   name varchar2(125) not null
);

insert into departments (
   id,
   name
) values ( 10,
           'Alpha' );
insert into departments (
   id,
   name
) values ( 20,
           'Beta' );
insert into departments (
   id,
   name
) values ( 30,
           'Gama' );

commit;

DESC departments;


SET LINESIZE 500;
SET TRIMSPOOL ON;
column name format a20;


select *
  from departments;

create table countries (
   id    number
      generated by default as identity start with 11 increment by 10
   primary key,
   name  varchar2(125) not null,
   ruler varchar2(255) not null
);
DESC countries;

insert into countries (
   id,
   name,
   ruler
) values ( 21,
           'USA',
           'Trump' );
insert into countries (
   id,
   name,
   ruler
) values ( 11,
           'India',
           'Modi' );
insert into countries (
   id,
   name,
   ruler
) values ( 41,
           'Germany',
           'Dravid' );

commit;

   SET LINESIZE 500;
SET TRIMSPOOL ON;
column name format a20;
column ruler format a20;

select *
  from countries;

create table cities (
   id         number
      generated by default as identity start with 101 increment by 1
   primary key,
   name       varchar2(125) not null,
   admin      varchar2(255) not null,
   country_id number not null
);
DESC cities;
insert into cities (
   id,
   name,
   admin,
   country_id
) values ( 101,
           'Nellore',
           'Nimisha',
           21 );
insert into cities (
   id,
   name,
   admin,
   country_id
) values ( 102,
           'Tanjore',
           'Pithcumani',
           11 );
insert into cities (
   id,
   name,
   admin,
   country_id
) values ( 103,
           'Mumbai',
           'Sana',
           11 );
insert into cities (
   id,
   name,
   admin,
   country_id
) values ( 105,
           'Kollam',
           'Vishak',
           31 );

commit;

   SET LINESIZE 500;
SET TRIMSPOOL ON;
column name format a20;
column admin format a20;

select *
  from cities;

create table employees (
   id            number
      generated by default as identity start with 1 increment by 1
   primary key,
   name          varchar2(125) not null,
   job_title     varchar2(125) not null,
   department_id number not null,
   address       varchar2(1000) not null,
   city_id       number not null
);
DESC employees;

insert into employees (
   id,
   name,
   job_title,
   department_id,
   address,
   city_id
) values ( 1,
           'Athira',
           'SE',
           10,
           '----',
           101 );
insert into employees (
   id,
   name,
   job_title,
   department_id,
   address,
   city_id
) values ( 2,
           'Ayisha',
           'Tester',
           20,
           '----',
           102 );
insert into employees (
   id,
   name,
   job_title,
   department_id,
   address,
   city_id
) values ( 3,
           'Dhaheen',
           'Analyst',
           20,
           '----',
           103 );
insert into employees (
   id,
   name,
   job_title,
   department_id,
   address,
   city_id
) values ( 4,
           'Venkatesh',
           'SE',
           30,
           '----',
           103 );
insert into employees (
   id,
   name,
   job_title,
   department_id,
   address,
   city_id
) values ( 5,
           'minhaj',
           'Tester',
           10,
           '----',
           101 );
insert into employees (
   id,
   name,
   job_title,
   department_id,
   address,
   city_id
) values ( 6,
           'Nayana',
           'SE',
           30,
           '----',
           104 );

commit;

select *
  from employees;

alter table employees add (
   salary number(8,2) default 0 not null,
   bonus  number(8,2) default 0 not null
);

select *
  from employees;

update employees
   set salary = 12000,
       bonus = 800
 where id = 1;
update employees
   set salary = 8000,
       bonus = 3000
 where id = 2;
update employees
   set salary = 13000,
       bonus = 600
 where id = 3;
update employees
   set salary = 7000,
       bonus = 3800
 where id = 4;
update employees
   set salary = 11000,
       bonus = 800
 where id = 5;
update employees
   set salary = 10000,
       bonus = 1000
 where id = 6;
commit;


-- JOIN Operations -->


-- to query emp_name, city_name 
-- to view which all employees are in which all cities
select employees.name as emp_name,
       cities.name as city_name
  from employees
 inner join cities
on employees.city_id = cities.id;

-- to query emp_name, city_name + extra employees
-- to view which all cities have assigned employees
select employees.name as emp_name,
       cities.name as city_name
  from employees
  left join cities
on employees.city_id = cities.id;

-- to query emp_name, city_name + extra cities
select employees.name as emp_name,
       cities.name as city_name
  from employees right
  join cities
on employees.city_id = cities.id;

-- to query emp_name, city_name + extra employees + extra cities
select employees.name as emp_name,
       cities.name as city_name
  from employees full
  join cities
on employees.city_id = cities.id;

-- to query emp_name, city_name + extra employees + extra cities + extra countries
select employees.name as emp_name,
       cities.name as city_name,
       countries.name as country_name
  from employees full
  join cities
on employees.city_id = cities.id
  full join countries
on cities.country_id = countries.id;

-- to query emp_name, city_name, country_name
select employees.name as emp_name,
       cities.name as city_name,
       countries.name as country_name
  from employees
 inner join cities
on employees.city_id = cities.id
 inner join countries
on cities.country_id = countries.id;

-- to query emp_name, city_name, country_name + extra countries
select employees.name as emp_name,
       cities.name as city_name,
       countries.name as country_name
  from employees
 inner join cities
on employees.city_id = cities.id
 right join countries
on cities.country_id = countries.id;